djangosrh/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("payments", view=views.PaymentListView.as_view(), name="payments"),
    path("toggle_payment_active_status", view=views.toggle_payment_active_status, name="toggle_payment_active_status"),
    path("upload_payment_csv", view=views.upload_payment_csv, name="upload_payment_csv"),
]

djangosrh/djangosrh/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ital/', include('ital.urls', namespace="ital")),
    path("", include("django.contrib.auth.urls")),
    path('core/', view=include('core.urls')),
    path('concert/', view=include('concert.urls', namespace="concert")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangosrh/ital/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("show_reservation/<str:uuid>", views.show_reservation, name="show_reservation"),
    path("reservations", view=views.ReservationListView.as_view(), name="reservations"),
    path("events/<int:event_id>/reservation_form", views.reservation_form, name="reservation_form"),
    path("send_payment_reception_confirmation", views.send_payment_reception_confirmation, name="send_payment_reception_confirmation"),
    path("events/<int:event_id>/item_tickets", views.item_tickets, name="item_tickets"),
    path("events/<int:event_id>/export_csv", views.export_csv, name="export_csv"),
]

djangosrh/concert/models.py
from collections import namedtuple
from collections.abc import Iterator
from random import choices
import uuid

from django.db import models

from core.models import BaseReservation, BaseEvent


class Event(BaseEvent):
    class Meta:
        # because I want Choice to link to "concert" Events, not to BaseEvents where they could also be "ital" Events:
        proxy = False
    base_event_ptr = models.OneToOneField(BaseEvent,
                                          on_delete=models.CASCADE,
                                          parent_link=True,
                                          primary_key=True,
                                          related_name="%(class)s_set",
                                          related_query_name="%(app_label)s_%(class)ss")

    def occupied_seats(self) -> int:
        return (
            ReservationChoiceCount.objects
            .filter(reservation__event=self)
            .aggregate(total=models.Sum("count"))["total"] or 0
        )

    ChoiceSummary = namedtuple("ChoiceSummary", "id,display_text,display_text_plural,column_header,total_count")
    def reservation_choices(self) -> list[ChoiceSummary]:
        return list(
            self.ChoiceSummary(
                id=itm["choice__id"],
                display_text=itm["choice__display_text"],
                display_text_plural=itm["choice__display_text_plural"],
                column_header=itm["choice__column_header"],
                total_count=itm["total_count"]
            ) for itm in
        ReservationChoiceCount.objects
        .filter(reservation__event_id=self.id)
        .values("choice__display_text", "choice__id", "choice__display_text", "choice__display_text_plural", "choice__column_header")
        .annotate(total_count=models.Sum("count", default=0))
        .order_by("choice__id")
    )


class Choice(models.Model):
    "What a customer chooses"
    price_in_cents = models.PositiveIntegerField()
    available_in = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name="%(class)s_set",
        related_query_name="%(app_label)s_%(class)ss")
    display_text = models.CharField(max_length=200, blank=False)
    display_text_plural = models.CharField(max_length=200, blank=False)
    column_header = models.CharField(max_length=200, blank=False)

    def __str__(self):
        return self.display_text


class ReservationChoiceCount(models.Model):
    count = models.IntegerField()
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['choice_id', 'reservation_id'], name='%(app_label)s_%(class)s_reservation*choice'),
            # TODO: constrain all choices to be for the same event
        ]

    def __repr__(self):
        return f"<ReservationChoiceCount {self.id}, {self.count}* from {self.choice}>"


class Reservation(BaseReservation):
    base_reservation_ptr = models.OneToOneField(BaseReservation,
                                                on_delete=models.CASCADE,
                                                parent_link=True,
                                                primary_key=True,
                                                related_name="%(class)s_set",
                                                related_query_name="%(app_label)s_%(class)ss")
    event = models.ForeignKey("Event",
                              on_delete=models.CASCADE,
                              related_name="%(class)s_set",
                              related_query_name="%(app_label)s_%(class)ss")

    class Meta:
        # Specify a unique related name for reverse access
        verbose_name = "Réservation concert"
        verbose_name_plural = "Réservations concert"

    def save(self, **kwargs):
        if not hasattr(self, 'base_event') or self.base_event is None:
            self.base_event = self.event.base_event_ptr
        super().save(**kwargs)

    @property
    def places(self) -> int:
        return self.reservationchoicecount_set.aggregate(models.Sum('count')).get('count__sum', 0)

djangosrh/ital/views.py
import csv
from datetime import UTC, date, datetime, timedelta
import itertools
import time
from collections.abc import Iterator
from typing import Any, Mapping

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import login_required
from django.core.mail import EmailMultiAlternatives
from django.db.models import Exists, OuterRef, Prefetch, QuerySet, Subquery, Sum, IntegerField, CharField
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import html
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView

import qrcode
from qrcode.image.svg import SvgPathFillImage

from core.banking import cents_to_euros, format_bank_id, generate_payment_QR_code_content

from core.models import Payment, ReservationPayment, get_reservations_with_likely_payments
from core.views import aux_send_payment_reception_confirmation
from .forms import ItemTicketsGenerationForm, ReservationForm
from .models import Choice, DishType, Event, Item, Reservation, ReservationItemCount
from .templatetags.currency_filter import plural

def index(request):
    return render(request, "ital/index.html")


def show_reservation(request, uuid: str) -> HttpResponse:
    reservation = get_object_or_404(Reservation, uuid=uuid)
    items: list[dict[str, str|int]] = [
        itm | { "display_text_with_plural": (itm["item__display_text"], itm["item__display_text_plural"])}
        for itm in
        reservation.reservationitemcount_set
        .order_by('item__dish', 'item__display_text')
        .values("item__dish", "item__display_text", "item__display_text_plural")
        .annotate(total_count=Sum("count", default=0))
    ]
    remaining_due = (
        reservation.total_due_in_cents -
        reservation.reservationpayment_set.aggregate(
            Sum("payment__amount_in_cents", default=0))['payment__amount_in_cents__sum'])
    return render(request, "ital/show_reservation.html", {
        "reservation": reservation,
        "remaining_amount_due_in_cents": remaining_due,
        "items": items,
        "payment_qrcode": qrcode.make(
            generate_payment_QR_code_content(
                remaining_due,
                bank_id=reservation.bank_id,
                bank_account=reservation.event.bank_account,
                organizer_bic=reservation.event.organizer_bic,
                organizer_name=reservation.event.organizer_name),
            image_factory=SvgPathFillImage
        ).to_string().decode('utf8'),
        "page_qrcode": qrcode.make(
            request.build_absolute_uri(), image_factory=SvgPathFillImage
        ).to_string().decode('utf8')})


class ReservationListView(LoginRequiredMixin, ListView):
    event_id: int | None = None
    event: Event | None = None
    template_name = "ital/reservations.html"
    context_object_name = "reservations"
    paginate_by = 20

    def setup(self, request, *args, **kwargs) -> None:
        super().setup(request, *args, **kwargs)
        self.event = (
            Event.objects.filter(disabled=False).order_by("date").first()
            if (event_id := request.GET.get('event_id')) is None
            else get_object_or_404(Event, id=event_id))
        self.event_id = None if self.event is None else self.event.id

    def get_queryset(self):
        return get_reservations_with_likely_payments(
            date(2025, 2, 12)
            if self.event is None else
            (self.event.date - timedelta(days=90)),
            Reservation.objects.filter(event_id=self.event_id).order_by("id"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.event is not None:
            context["event"] = self.event
            context["total_count"] = self.event.occupied_seats()
        return context


@csrf_exempt
def reservation_form(request, event_id: int) -> HttpResponse:
    try:
        if request.method == "POST" or request.GET.get("force") == "True":
            reservation_cookie = None
        else:
            # Check for recent reservations in the session
            reservation_cookie = request.session.get("recent_reservation")

        if (reservation_cookie
            and (uuid := reservation_cookie.get("uuid"))
            and (reservation_time := reservation_cookie.get("time"))
            and (time.time() > reservation_time)
            and (time.time() - reservation_time <= 30 * 60)
            and (recent_reservation := Reservation.objects.get(uuid=uuid))):
            return render(
                request,
                "ital/double_reservation.html",
                {"reservation": recent_reservation})
    except Exception:
        pass

    event = get_object_or_404(Event, pk=event_id)
    if event.disabled or event.occupied_seats() >= event.max_seats:
        return render(request, "ital/event_disabled.html", context={"event": event})

    if request.method == "POST":
        form = ReservationForm(event, data=request.POST)
        if reservation := form.save():
            # Store reservation info in the session
            request.session["recent_reservation"] = {"uuid": str(reservation.uuid), "time": time.time()}
            return HttpResponseRedirect(reverse("ital:show_reservation", kwargs={"uuid": reservation.uuid}))
        else:
            return render(
                request,
                "ital/reservation_form.html",
                {"form": form}, status=422)
    return render(request, "ital/reservation_form.html", {
        "form": ReservationForm(event)})


@login_required
def send_payment_reception_confirmation(request) -> HttpResponseRedirect:
    return aux_send_payment_reception_confirmation(request, Event, "ital:reservations", "ital:show_reservation")


@login_required
def item_tickets(request, event_id: int):
    event = get_object_or_404(Event, pk=event_id)
    if event.disabled:
        return render(request, "ital/event_disabled.html", context={"event": event})

    if request.method == "POST":
        form = ItemTicketsGenerationForm(event, data=request.POST)
        if form.is_valid():
            return render_generated_tickets(request, form)
        else:
            return render(
                request,
                "ital/item_tickets_form.html",
                {"form": form}, status=422)

    return render(request, "ital/item_tickets_form.html", {
        "form": ItemTicketsGenerationForm(event)})


@login_required
def render_generated_tickets(request, form: ItemTicketsGenerationForm) -> HttpResponse:
    return render(
        request,
        "ital/item_tickets.html",
        {"form": form,
         "reservations": list(create_full_ticket_list(form)),
         "MEDIA_URL": settings.MEDIA_URL}
    )


def create_full_ticket_list(form: ItemTicketsGenerationForm) -> Iterator[Any]:
    dish_names = {DishType.DT0STARTER: "Entrée", DishType.DT1MAIN: "Plat", DishType.DT2DESSERT: "Dessert"}
    for r in form.event.reservation_set.order_by("last_name", "first_name"):
        if not (tickets := create_tickets_for_one_reservation(r)):
            continue
        for itm in tickets["items"]:
            form.decrease_item_count(itm["item_id"], itm["total_count"])
            itm["item__dish"] = dish_names[itm["item__dish"]]
        tickets["items"] = list(itertools.chain(*(itertools.repeat(datdict, datdict["total_count"]) for datdict in tickets["items"])))
        tickets["reservation"] = r
        yield tickets
    if all(cnt <= 0 for cnt in form.data.values()):
        return
    yield {
        "reservation": {
            "no_amount_due": True,
            "full_name": "Tickets de réserve",
        },
        "total_tickets": sum(cnt for cnt in form.data.values() if cnt > 0),
        "ticket_details": ', '.join(
            plural(form.data[key], [itm.display_text, itm.display_text_plural])
            for key, itm in form.reference_data.items()
            if form.data[key] > 0),
        "items": list(itertools.chain(*(itertools.repeat(
            {
            "item_id": val.id,
            "item__short_text": (itm := Item.objects.get(pk=val.id)).short_text,
            "item__display_text": itm.display_text,
            "item__display_text_plural": itm.display_text_plural,
            "item__image": itm.image,
            "item__dish": dish_names[itm.dish],
            }, form.data[key]) for key, val in form.reference_data.items()))),
    }


def create_tickets_for_one_reservation(r: Reservation) -> dict[str, int | str | list[dict[str, int | str]]]:
    items = list(
        r.reservationitemcount_set.order_by('item__dish', 'item_id')
        .values(
            "item_id",
            "item__short_text",
            "item__display_text",
            "item__display_text_plural",
            "item__image",
            "item__dish",
        )
        .annotate(total_count=Sum("count"))
    )
    return {
        'total_tickets': total_tickets,
        'ticket_details': ', '.join(
            plural(itm['total_count'], [itm['item__display_text'], itm['item__display_text_plural']])
            for itm in items),
        'items': items,
    } if (total_tickets := sum(itm['total_count'] for itm in items)) > 0 else {}


@login_required
def export_csv(request, event_id: int) -> HttpResponse:
    event = get_object_or_404(Event, pk=event_id)
    if event.disabled:
        return render(request, "ital/event_disabled.html", context={"event": event})
    reservation_items = event.reservation_items()
    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="reservations.csv"'},
    )
    writer = csv.writer(response)
    writer.writerow(["Nom", "Places", "Valeur", "Déjà payé", "Restant dû", *(
        itm.column_header for itm in reservation_items), "Commentaire"])

djangosrh/ital/templates/ital/base_template.html
<!DOCTYPE HTML>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SRH Braine-l'Alleud{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css">
    <link rel="stylesheet" href="https://srhbraine.be/css/app.css">
    <style>
      {% block style %}{% endblock %}
    </style>
  </head>
  <body>
    <!-- navbar -->
    <nav id="navbar" class="navbar navbar-expand-lg bg-light fixed-top">
      <div class="container">
        <a class="navbar-brand" href="https://srhbraine.be/index.php">
          <img src="https://srhbraine.be/images/logo-srh.png" style="width: 90px;" alt="Responsive image">&nbsp;SRH</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item">
              <a class="nav-link" href="https://srhbraine.be/index.php#home">Accueil</a></li>
            <li class="nav-item">
              <a class="nav-link" href="https://srhbraine.be/index.php#services">Qui sommes-nous ?</a></li>
            <li class="nav-item">
              <a class="nav-link" href="https://srhbraine.be/index.php#work">Galeries</a></li>
            <li class="nav-item">
              <a class="nav-link" href="https://srhbraine.be/index.php#sponsors">Sponsors</a></li>
            <li class="nav-item">
              <a class="nav-link" href="https://srhbraine.be/liens.php">Liens</a></li>
            <li class="nav-item">
              <a class="nav-link" href="https://srhbraine.be/agenda.php">Agenda</a></li>
            <li class="nav-item">
              <a class="nav-link" href="https://srhbraine.be/index.php#blog">Blog</a></li>
            <li class="nav-item">
              <a class="nav-link" href="https://srhbraine.be/index.php#contact">Contact</a></li></ul>
          <ul class="navbar-nav flex-row">
            <li class="nav-item">
              <a class="social-icon" href="https://www.facebook.com/societeroyaleharmonie/" target="_blank">
                <i class="ri-facebook-line"></i></a></li>
            <li class="nav-item">
              <a class="social-icon" href="https://www.instagram.com/srh_braine/" target="_blank">
                <i class="ri-instagram-line"></i></a></li>
            <li class="nav-item">
              <a class="social-icon" href="https://www.youtube.com/@raphaeldagostino" target="_blank">
                <i class="ri-youtube-line"></i></a></li></ul></div></div></nav>
    <section class="section-padding">
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </section>
    <section class="section-padding row">
      <footer class="footer-bottom">
        <div class="container">
          <div class="row col-12">
            <p class="mb-0">Retour au <a href="https://srhbraine.be/">site de la Société Royale d'Harmonie de Braine-l'Alleud</a>.</p></div></div></footer></section></body></html>

djangosrh/ital/templates/ital/double_reservation.html
{% extends "core/base_template.html" %}
{% load currency_filter %}
{% block title %}{{ reservation.full_name }} - {{ reservation.event.name }}{% endblock %}
{% block content %}
<p>
  Vous avez déjà une réservation au nom de {{ reservation.full_name }} pour {{ reservation.places|plural:"place" }} le {{ reservation.event.date|french_date }} que vous pouvez <a class="link-primary" href="{% url 'ital:show_reservation' reservation.uuid %}">visualiser ici</a>.
</p>
<p>
  Si au lieu de voir <a class="link-primary" href="{% url 'ital:show_reservation' reservation.uuid %}">votre ancienne réservation</a>, vous voulez vraiment <a class="link-underline-primary" href="{% url 'ital:reservation_form' reservation.event_id %}?force=True">faire une nouvelle réservation, confirmez en cliquant ici</a>.
</p>
{% endblock %}

djangosrh/ital/templates/ital/index.html
<html>
  <head>
    <title>Reservation application for italian evening</title>
  </head>
  <body>
    <a class="link-primary" href="{% url 'ital:reservations' %}">List of reservations</a>
  </body>
</html>

djangosrh/ital/templates/ital/item_tickets.html
{% extends "core/base_template.html" %}
{% load currency_filter %}
{% block title %}Tickets for {{ form.event.name }}{% endblock %}
{% block style %}
div.tickets {
    display: grid;
    grid-template-columns: 38vw 10vw 38vw 10vw;
    margin-left: auto;
    margin-right: auto;
}

div.tickets > div.ticket-left-col > div:nth-child(1) {
    margin-top: auto;
    margin-bottom: 0px;
}

div.tickets > div.ticket-left-col > div:nth-child(2) {
    margin-top: auto;
    margin-bottom: auto;
}

div.tickets > div.ticket-left-col > div:nth-child(3) {
    margin-top: auto;
    margin-bottom: 0px;
    font-weight: bold;
}

div.tickets > div.ticket-left-col > div:nth-child(4) {
    margin-top: 0px;
    margin-bottom: auto;
    font-variant-caps: small-caps;
}

div.tickets > div.ticket-left-col {
    display: grid;
    grid-template-rows: auto auto auto auto;
    padding-left: 0.6cm;
}

div.tickets > div > img {
    width: 95%;
    position: relative;
    left: -0.6cm;
    top: 50%;
    transform: translateY(-50%);
}

div.ticket-heading {
    padding-top: 1ex;
    font-weight: bold;
    font-size: larger;
}

@media print {
    nav { display: none; }
    .fixed-top { display: none; }
    .navbar { display: none; }
    a.navbar-brand { display: none; }
    footer { display: none; }
    div.tickets {
        grid-template-columns: 7cm 2.5cm 7cm 2.5cm;
        page-break-after: auto;
        page-break-before: avoid;
        border-top: dimgray dashed 0.05cm;
    }
    div.tickets > div.ticket-left-col {
        page-break-inside: avoid;
        page-break-after: auto;
        page-break-before: avoid;
        grid-template-rows: 1cm 1cm 1cm 1cm;
    }
    div.tickets > div {
        border-bottom: dimgray dashed 0.05cm;
    }
    div.tickets > div.ticket-left-col:nth-child(4n+3) {
        border-left: dimgray dashed 0.05cm;
    }
    div.no-print-page-break {
        page-break-inside: avoid;
        page-break-after: avoid;
    }
}
{% endblock %}
{% block content %}
{% for res in reservations %}
<div class="no-print-page-break">
  <div class="ticket-heading">{{ res.reservation.full_name }} {{ res.reservation.places|plural:"place" }}</div>
  <div>{% if res.no_amount_due %}Total dû: {{ res.reservation.remaining_amount_due_in_cents|cents_to_euros }} pour {% endif %}{{ res.total_tickets|plural:"ticket" }}. {{ res.ticket_details }}</div>
  <div class="tickets">
    {% for itm in res.items %}
    <div class="ticket-left-col">
      <div>table n°</div>
      <div>serveur</div>
      <div>{{ itm.item__dish }}</div>
      <div>{{ itm.item__short_text }}</div>
    </div>
    <div>{% if itm.item__image %}<img src="{{ MEDIA_URL }}{{ itm.item__image }}">{% endif %}</div>
    {% endfor %}
  </div>
</div>
{% endfor %}
{% endblock %}

djangosrh/ital/templates/ital/item_tickets_form.html
{% extends "core/base_template.html" %}
{% load currency_filter %}
{% block title %}Generate tickets for {{ form.event.name }}{% endblock %}
{% block style %}
input[type="number"].form-control { padding-left: 0; padding-right: 0; }
input[type="number"].col-form-control { padding-left: 0; padding-right: 0; }
{% endblock %}
{% block content %}
<form id="item_tickets_generation_form_id" action="{% url 'ital:item_tickets' form.event.id %}" method="post">
  {% csrf_token %}
  <div class="container">
    {% for field_id, val, itm, errors in form.zip_values %}
    <div class="form-group row">
      <label class="col-sm-10 col-form-label" for="{{ field_id }}">{{ itm.display_text }}: {{ itm.total_count|plural:"réservation" }}</label>
      <div class="col-sm-2">
        <input class="form-control {% if form.was_validated %}{% if errors %}is-invalid{% else %}is-valid{% endif %}{% endif %}" id="{{ field_id }}" name="{{ field_id }}" required="required" type="number" value="{{ itm.total_count }}" min="{{ itm.total_count }}">
      </div>
    </div>
    {% for err in errors %}<div class="row"><div class="col-sm-12 invalid-feedback" style="display: flex;">{{ err }}</div></div>{% endfor %}
    {% endfor %}
    <div class="row"><input class="form-control" type="submit" value="OK" id="form-submit"></div>
  </div>
</form>
{% endblock %}

djangosrh/ital/templates/ital/reservations.html
{% extends "core/base_template.html" %}
{% load currency_filter %}
{% block title %}{{ event.name }}{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      Il y a {{ event.reservation_set.count|plural:"réservation" }} pour {{ total_count|plural:"place" }}.
    </div>
    <div class="col-sm-2">
      <a class="link-primary" href="{% url 'ital:reservation_form' event.id %}">Nouvelle réservation</a>
    </div>
    <div class="col-sm-2">
      <a class="link-primary" href="{% url 'payments' %}">Gérer paiements</a>
    </div>
    <div class="col-sm-2">
      <a class="link-primary" href="{% url 'ital:item_tickets' event.id %}">Générer tickets</a>
    </div>
    <div class="col-sm-2">
      <a class="link-primary" href="{% url 'ital:export_csv' event.id %}">Exporter listes</a>
    </div>
    <div class="col-sm-1">
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Log Out</button>
      </form>
    </div>
  </div>
</div>
<ul>
{% for itm in event.reservation_items %}
  <li>{{ itm.total_count }} {% if itm.total_count == 1%}{{ itm.display_text }}{% else %}{{ itm.display_text_plural }}{% endif %}</li>
{% endfor %}
</ul>
{% if page_obj.has_previous or page_obj.has_next %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="link-primary" href="?page=1">&laquo; first</a>
            {% if page_obj.previous_page_number > 1 %}<a class="link-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>{% endif %}
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            {% if page_obj.next_page_number < page_obj.paginator.num_pages %}<a class="link-primary" href="?page={{ page_obj.next_page_number }}">next</a>{% endif %}
            <a class="link-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
<table>
  <thead>
    <tr>
      <th>Réservation</th>
      <th class="text-end">Places</th>
      <th class="text-end">Valeur</th>
      <th class="text-end">Payé</th>
      <th>Confirmer réception d'un paiement</th>
    </tr>
  </thead>
  <tbody>
    {% for reservation in reservations %}
    <tr>
      <td>
        <a class="link-primary" href="{% url 'ital:show_reservation' reservation.uuid %}">{{ reservation }}</a>
      </td>
      <td class="ps-1 text-end">{{ reservation.places }}</td>
      <td class="ps-1 text-end">{{ reservation.total_due_in_cents|cents_to_euros }}</td>
      <td class="ps-1 text-end">{{ reservation.total_received_in_cents|cents_to_euros }}</td>
      <td class="ps-1">{% if reservation.likely_payment_id %}<form method="POST" action="{% url 'ital:send_payment_reception_confirmation' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="hidden" name="payment_id" value="{{ reservation.likely_payment_id }}">
          <input type="hidden" name="reservation_id" value="{{ reservation.id }}">
          <input type="hidden" name="event_id" value="{{ event.id }}">
          <input type="submit" value="{{ reservation.likely_payment_other_name|default:reservation.likely_payment_other_account }}: {{ reservation.likely_payment_amount_in_cents|cents_to_euros }}"></form>{% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if page_obj.has_previous or page_obj.has_next %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="link-primary" href="?page=1">&laquo; first</a>
            {% if page_obj.previous_page_number > 1 %}<a class="link-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>{% endif %}
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            {% if page_obj.next_page_number < page_obj.paginator.num_pages %}<a class="link-primary" href="?page={{ page_obj.next_page_number }}">next</a>{% endif %}
            <a class="link-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}