djangosrh/concert/urls.py
from django.urls import path

from . import views

app_name = "concert"
urlpatterns = [
    path("", views.index, name="index"),
    path("reservations", views.ReservationListView.as_view(), name="reservations"),
    path("show_reservation/<str:uuid>", views.show_reservation, name="show_reservation"),
    path("events/<int:event_id>/reservation_form", views.reservation_form, name="reservation_form"),
    path("send_payment_reception_confirmation", views.send_payment_reception_confirmation, name="send_payment_reception_confirmation"),
    path("events/<int:event_id>/export_csv", views.export_csv, name="export_csv"),
]

djangosrh/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("payments", view=views.PaymentListView.as_view(), name="payments"),
    path("toggle_payment_active_status", view=views.toggle_payment_active_status, name="toggle_payment_active_status"),
    path("upload_payment_csv", view=views.upload_payment_csv, name="upload_payment_csv"),
]

djangosrh/djangosrh/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ital/', include('ital.urls', namespace="ital")),
    path("", include("django.contrib.auth.urls")),
    path('core/', view=include('core.urls')),
    path('concert/', view=include('concert.urls', namespace="concert")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangosrh/concert/models.py
from collections import namedtuple
from collections.abc import Iterator
from random import choices
import uuid

from django.db import models

from core.models import BaseReservation, BaseEvent


class Event(BaseEvent):
    class Meta:
        # because I want Choice to link to "concert" Events, not to BaseEvents where they could also be "ital" Events:
        proxy = False
    base_event_ptr = models.OneToOneField(BaseEvent,
                                          on_delete=models.CASCADE,
                                          parent_link=True,
                                          primary_key=True,
                                          related_name="%(class)s_set",
                                          related_query_name="%(app_label)s_%(class)ss")

    def occupied_seats(self) -> int:
        return (
            ReservationChoiceCount.objects
            .filter(reservation__event=self)
            .aggregate(total=models.Sum("count"))["total"] or 0
        )

    ChoiceSummary = namedtuple("ChoiceSummary", "id,display_text,display_text_plural,column_header,total_count")
    def reservation_choices(self) -> list[ChoiceSummary]:
        return list(
            self.ChoiceSummary(
                id=itm["choice__id"],
                display_text=itm["choice__display_text"],
                display_text_plural=itm["choice__display_text_plural"],
                column_header=itm["choice__column_header"],
                total_count=itm["total_count"]
            ) for itm in
        ReservationChoiceCount.objects
        .filter(reservation__event_id=self.id)
        .values("choice__display_text", "choice__id", "choice__display_text", "choice__display_text_plural", "choice__column_header")
        .annotate(total_count=models.Sum("count", default=0))
        .order_by("choice__id")
    )


class Choice(models.Model):
    "What a customer chooses"
    price_in_cents = models.PositiveIntegerField()
    available_in = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name="%(class)s_set",
        related_query_name="%(app_label)s_%(class)ss")
    display_text = models.CharField(max_length=200, blank=False)
    display_text_plural = models.CharField(max_length=200, blank=False)
    column_header = models.CharField(max_length=200, blank=False)

    def __str__(self):
        return self.display_text


class ReservationChoiceCount(models.Model):
    count = models.IntegerField()
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['choice_id', 'reservation_id'], name='%(app_label)s_%(class)s_reservation*choice'),
            # TODO: constrain all choices to be for the same event
        ]

    def __repr__(self):
        return f"<ReservationChoiceCount {self.id}, {self.count}* from {self.choice}>"


class Reservation(BaseReservation):
    base_reservation_ptr = models.OneToOneField(BaseReservation,
                                                on_delete=models.CASCADE,
                                                parent_link=True,
                                                primary_key=True,
                                                related_name="%(class)s_set",
                                                related_query_name="%(app_label)s_%(class)ss")
    event = models.ForeignKey("Event",
                              on_delete=models.CASCADE,
                              related_name="%(class)s_set",
                              related_query_name="%(app_label)s_%(class)ss")

    class Meta:
        # Specify a unique related name for reverse access
        verbose_name = "Réservation concert"
        verbose_name_plural = "Réservations concert"

    def save(self, **kwargs):
        if not hasattr(self, 'base_event') or self.base_event is None:
            self.base_event = self.event.base_event_ptr
        super().save(**kwargs)

    @property
    def places(self) -> int:
        return self.reservationchoicecount_set.aggregate(models.Sum('count')).get('count__sum', 0)

djangosrh/concert/views.py
import csv
from datetime import timedelta
import time

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import login_required
from django.core.mail import EmailMultiAlternatives
from django.db.models import Exists, OuterRef, Prefetch, QuerySet, Subquery, Sum, IntegerField, CharField
from django.http import Http404, HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import html
from django.views.generic import ListView
import qrcode
from qrcode.image.svg import SvgPathFillImage

from .forms import ReservationForm
from .models import Event, Reservation
from core.banking import cents_to_euros, format_bank_id, generate_payment_QR_code_content
from core.models import get_reservations_with_likely_payments
from core.views import aux_send_payment_reception_confirmation

def index(request):
    events = [(str(evt), reverse("concert:reservations", query={"event_id": evt.id}))
              for evt in Event.objects.filter(disabled=False).order_by("date")]
    return render(request, "concert/index.html", context={"events": events})


class ReservationListView(LoginRequiredMixin, ListView):
    event_id: int | None = None
    event: Event | None = None
    template_name = "concert/reservations.html"
    context_object_name = "reservations"
    paginate_by = 20

    def setup(self, request, *args, **kwargs) -> None:
        super().setup(request, *args, **kwargs)
        event_id = request.GET.get('event_id')
        if event_id is not None:
            try:
                event_id = int(event_id)
            except ValueError:
                raise Http404(f"Invalid event {event_id!r}.")
        self.event = (
            Event.objects.filter(disabled=False).order_by("date").first()
            if event_id is None
            else get_object_or_404(Event, id=event_id))
        self.event_id = None if self.event is None else self.event.id

    def get_queryset(self):
        return get_reservations_with_likely_payments(
            date(2025, 2, 12)
            if self.event is None else
            (self.event.date - timedelta(days=90)),
            Reservation.objects.filter(event_id=self.event_id).order_by("id"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.event is not None:
            context["event"] = self.event
            context["total_count"] = self.event.occupied_seats()
        return context


def reservation_form(request, event_id: int) -> HttpResponse:
    try:
        if request.method == "POST" or request.GET.get("force") == "True":
            reservation_cookie = None
        else:
            # Check for recent reservations in the session
            reservation_cookie = request.session.get("recent_reservation")

        if (reservation_cookie
            and (uuid := reservation_cookie.get("uuid"))
            and (reservation_time := reservation_cookie.get("time"))
            and (time.time() > reservation_time)
            and (time.time() - reservation_time <= 30 * 60)
            and (recent_reservation := Reservation.objects.get(uuid=uuid))):
            return render(
                request,
                "concert/double_reservation.html",
                {"reservation": recent_reservation, "event_id": event_id})
    except Exception:
        pass

    event = get_object_or_404(Event, pk=event_id)
    if event.disabled or event.occupied_seats() >= event.max_seats:
        return render(request, "concert/event_disabled.html", context={"event": event})

    if request.method == "POST":
        form = ReservationForm(event, data=request.POST)
        if reservation := form.save():
            # Store reservation info in the session
            request.session["recent_reservation"] = {"uuid": str(reservation.uuid), "time": time.time()}
            return HttpResponseRedirect(reverse("concert:show_reservation", kwargs={"uuid": reservation.uuid}))
        else:
            return render(
                request,
                "concert/reservation_form.html",
                {"form": form}, status=422)
    return render(request, "concert/reservation_form.html", {
        "form": ReservationForm(event)})


def show_reservation(request: HttpRequest, uuid: str) -> HttpResponse:
    reservation = get_object_or_404(Reservation, uuid=uuid)
    choices: list[dict[str, str|int]] = [
        chc | { "display_text_with_plural": (chc["choice__display_text"], chc["choice__display_text_plural"])}
        for chc in
        reservation.reservationchoicecount_set
        .order_by('choice__display_text')
        .values("choice__display_text", "choice__display_text_plural", "count")
    ]
    remaining_due = (
        reservation.total_due_in_cents -
        reservation.reservationpayment_set.aggregate(
            Sum("payment__amount_in_cents", default=0))['payment__amount_in_cents__sum'])
    return render(request, "concert/show_reservation.html", {
        "reservation": reservation,
        "remaining_amount_due_in_cents": remaining_due,
        "choices": choices,
        "payment_qrcode": qrcode.make(
            generate_payment_QR_code_content(
                remaining_due,
                bank_id=reservation.bank_id,
                bank_account=reservation.event.bank_account,
                organizer_bic=reservation.event.organizer_bic,
                organizer_name=reservation.event.organizer_name),
            image_factory=SvgPathFillImage
        ).to_string().decode('utf8'),
        "page_qrcode": qrcode.make(
            request.build_absolute_uri(), image_factory=SvgPathFillImage
        ).to_string().decode('utf8')})
   


@login_required
def send_payment_reception_confirmation(request) -> HttpResponseRedirect:
    return aux_send_payment_reception_confirmation(request, Event, "concert:reservations", "concert:show_reservation")


@login_required
def export_csv(request, event_id: int) -> HttpResponse:
    event = get_object_or_404(Event, pk=event_id)
    if event.disabled:
        return render(request, "ital/event_disabled.html", context={"event": event})
    reservation_choices = event.reservation_choices()
    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="reservations.csv"'},
    )
    writer = csv.writer(response)
    writer.writerow(["Nom", "Places", "Valeur", "Déjà payé", "Restant dû", *(
        chc.column_header for chc in reservation_choices), "Commentaire"])
    # N+1 queries, so what... I won't have that many reservations anyway.
    for res in event.reservation_set.order_by('last_name', 'first_name'):
        total_due = res.total_due_in_cents
        remaining = res.remaining_amount_due_in_cents()
        choice_counts = {res_chc_count.choice.id: res_chc_count.count for res_chc_count in res.reservationchoicecount_set.all()}
        writer.writerow([
            res.full_name,
            str(res.places),
            cents_to_euros(total_due),
            cents_to_euros(total_due - remaining),
            cents_to_euros(remaining),
            *(choice_counts.get(chc.id, 0) for chc in reservation_choices),
            res.extra_comment])
    return response

djangosrh/concert/templates/concert/double_reservation.html
{% extends "core/base_template.html" %}
{% load currency_filter %}
{% block title %}{{ reservation.full_name }} - {{ reservation.event.name }}{% endblock %}
{% block content %}
<p>
  Vous avez déjà une réservation au nom de {{ reservation.full_name }} pour {{ reservation.places|plural:"place" }} le {{ reservation.event.date|french_date }} que vous pouvez <a class="link-primary" href="{% url 'concert:show_reservation' reservation.uuid %}">visualiser ici</a>.
</p>
<p>
  Si au lieu de voir <a class="link-primary" href="{% url 'concert:show_reservation' reservation.uuid %}">votre ancienne réservation</a>, vous voulez vraiment <a class="link-underline-primary" href="{% url 'concert:reservation_form' event_id %}?force=True">faire une nouvelle réservation, confirmez en cliquant ici</a>.
</p>
{% endblock %}

djangosrh/concert/templates/concert/event_disabled.html
{% extends "core/base_template.html" %}
{% block title %}{{ event.name }}{% endblock %}
{% block content %}
<p>
  Hélas, nous n'acceptons pas de réservations pour l'événement '{{ event.name }}' pour le moment.  Vous pouvez <a class="link-primary" href="mailto:{{ event.contact_email }}">nous contacter par courrier électronique ({{ event.contact_email }})</a> pour plus de renseignements.
</p>
{% endblock %}

djangosrh/concert/templates/concert/index.html
<html>
  <head>
    <title>Reservation application for concerts</title>
  </head>
  <body>
    <ul>
      {% for name, link in events %}
      <li><a class="link-primary" href="{{ link }}">{{ name }}: List of reservations</a></li>
      {% endfor %}
    </ul>
  </body>
</html>

djangosrh/concert/templates/concert/reservation_form.html
{% extends "core/base_template.html" %}
{% load currency_filter %}
{% block title %}{{ form.event.name }}{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
{# Add via JS because our CMS doesn't like us adding our own CSS #}
<script>
  let style = document.createElement('style');
  style.innerHTML = `
select.form-control { padding-left: 0.25em; padding-right: 0.25em; }
input.form-control { padding-left: 0.25em; padding-right: 0.25em; }
input.col-form-control { padding-left: 0.25em; padding-right: 0.25em; }
input[type="number"].form-control { padding-left: 0; padding-right: 0; }
input[type="number"].col-form-control { padding-left: 0; padding-right: 0; }
form#reservation_form_id div.error-message { display: none; }
form#reservation_form_id div.is-invalid div.error-message { display: inline; }
`;
  document.head.appendChild(style);
</script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
      const errorClass = 'is-invalid';
      const form = document.querySelector('#reservation_form_id');
      const prices = {
          {% for inpt in form.choices %}
          '{{ inpt.id }}': {{ inpt.choice.price_in_cents }},
          {% endfor %}
      };
      function sumOfInputFields(inputFieldIds) {
          return inputFieldIds.reduce((sum, fieldId) => sum + parseInt(document.getElementById(fieldId).value),
                                      0);
      }
      function runValidation(input_id) {
          const input_field = document.getElementById(input_id);
          const val = parseInt(input_field.value);
          if (!Number.isNaN(val) && (0 <= val) && (val < 100)) {
              input_field.classList.remove(errorClass);
              return val;
          }
          input_field.classList.add(errorClass);
          return 0;
      }
      function validateAll() {
          let total_places = 0;
          for (let key in prices) {
              total_places += runValidation(key);
          }
          if (total_places < 1) {
              for (let key in prices) {
                  document.getElementById(key).classList.add(errorClass);
              }
          }
      }
      form.addEventListener('submit', function (event) {
          // Reset error classes
          resetErrorClasses();
          validateAll();
          // Prevent form submission if there are errors
          if (form.querySelectorAll('.' + errorClass).length > 0) {
              event.preventDefault();
          }
      });
      function updatePrice() {
          let totalPrice = 0;
          for (let key in prices) {
              const val = document.getElementById(key).value;
              const val_num = val == ''?0:parseInt(val);
              totalPrice += (val_num < 1?0:val_num) * prices[key];
          }
          if (totalPrice < 0) {
              totalPrice = 0;
          }
          const cents = String(totalPrice % 100).padStart(2, '0');
          const has_errors = (form.querySelectorAll('.' + errorClass).length > 0);
          const confirm_or_fix = has_errors?'Vérifiez votre commande':'Cliquez pour confirmer';
          const submit_button = document.getElementById('reservation-submit');
          submit_button.value = (Number.isNaN(totalPrice) || (totalPrice == 0))?confirm_or_fix:`${confirm_or_fix}. Prix total: ${totalPrice / 100}.${cents}€`
          if (has_errors) {
              submit_button.disabled = "disabled";
          } else {
              submit_button.removeAttribute("disabled");
          }
      }
      form.addEventListener('change', function (event) {
          validateAll();
          updatePrice();
      });
      function resetErrorClasses() {
          var errorSections = form.querySelectorAll('.' + errorClass);
          errorSections.forEach(function (section) {
              section.classList.remove(errorClass);
          });
      }
      resetErrorClasses();
      validateAll();
      updatePrice();
  });
</script>
<h1>{{ form.event.name }}</h1><h2>{{ form.event.date.day }}/{{ form.event.date.month }}/{{ form.event.date.year }}</h2>{% if form.event.extra_info %}<p>{{ form.event.extra_info }}</p>{% endif %}
<form id="reservation_form_id" action="{% url 'concert:reservation_form' form.event.id %}" method="post">
  {% csrf_token %}
  {% if form.was_validated and form.errors %}
  <div class="row g-0 invalid-feedback" style="display: inline;">{% for err in form.errors %}{{ err }}{% if not forloop.last %}<br>{% endif %}{% endfor %}</div>
  {% endif %}
  <div class="row g-0" style="display: flex;">
    <div class="col-sm-1">
      <select class="form-control {% if form.was_validated %}{% if form.first_name.errors %}is-invalid{% else %}is-valid{% endif %}{% endif %}" id="{{ form.civility.id }}" name="{{ form.civility.name }}">
        <option value="" selected="selected">???</option>
        <option value="Mlle">Mlle</option>
        <option value="Mme">Mme</option>
        <option value="Mr">Mr</option>
      </select>
    </div>
    <div class="col-sm-4">
      <input class="form-control {% if form.was_validated %}{% if form.first_name.errors %}is-invalid{% else %}is-valid{% endif %}{% endif %}" id="{{ form.first_name.id }}" name="{{ form.first_name.name }}" type="text" value="{{ form.first_name.value }}" placeholder="Prénom">
    </div>
    <div class="col-sm-7">
      <input class="form-control {% if form.was_validated %}{% if form.last_name.errors %}is-invalid{% else %}is-valid{% endif %}{% endif %}" id="{{ form.last_name.id }}" name="{{ form.last_name.name }}" required="required" type="text" value="{{ form.last_name.value }}" placeholder="Nom de famille">{% if form.last_name.errors %}{% for err in form.last_name.errors %}<span class="invalid-feedback">{{ err }}</span>{% endfor %}{% endif %}
    </div>
  </div>
  <div class="form-group row g-0">
    <label class="col-sm-2 col-form-label" for="{{ form.email.id }}">E-mail</label>
    <div class="col-sm-10">
      <input class="form-control {% if form.was_validated %}{% if form.email.errors %}is-invalid{% else %}is-valid{% endif %}{% endif %}" id="{{ form.email.id }}" name="{{ form.email.name }}" required="required" type="email" value="{{ form.email.value }}">
      {% for err in form.email.errors %}<span class="invalid-feedback">{{ err }}</span>{% endfor %}
    </div>
  </div>
  <div class="form-group">
    <small class="form-text text-muted">La Société Royale d&#8217;Harmonie de Braine-l&#8217;Alleud respecte votre vie privée. Les données de contact que vous nous communiquez dans ce formulaire seront uniquement utilisées dans le cadre de ce {{ form.event.name }}, à moins que vous nous donniez l&#8217;autorisation de les garder pour vous informer de nos concerts et autres fêtes dans le futur. Contactez <a class="link-primary" href="mailto:{{ form.event.contact_email }}">{{ form.event.contact_email }}</a> pour demander d&#8217;être retiré de nos fichiers.</small>
    <div class="form-check">
      <input class="form-check-input" id="{{ form.accepts_rgpd_reuse.id }}" name="{{ form.accepts_rgpd_reuse.name }}" type="checkbox" value="yes"{% if form.accepts_rgpd_reuse.value %}checked="checked"{% endif %}>
      <label for="{{ form.accepts_rgpd_reuse.id }}">Je désire être tenu au courant des activités futures de la SRH de Braine-l&#8217;Alleud et l&#8217;autorise à conserver mon nom et mon adresse email à cette fin.</label>
    </div>
  </div>
  <div class="container px-0">
    {% for inpt in form.choices %}
    <div class="form-group row g-0">
      <div style="width: {% if form.was_validated %}4em{% else %}3em{% endif %};">
        <input class="{% if form.was_validated %}{% if inpt.errors %}is-invalid{% else %}is-valid{% endif %}{% endif %} form-control" style="width: {% if form.was_validated %}4em{% else %}3em{% endif %}; padding-left: 0.1em; padding-right: 0.1em" id="{{ inpt.id }}" name="{{ inpt.name }}" value="{{ inpt.value }}" type="text" inputmode="numeric" pattern="\d\d?">
      </div>
      <div style="width: calc(100% - {% if form.was_validated %}4em{% else %}3em{% endif %} - 0.3em)">
        {% if inpt.errors %}<details class="text-white bg-danger"><summary>{% endif %}<label class="form-label" for="{{ inpt.id }}">{{ inpt.choice }} {{ inpt.choice.price_in_cents|cents_to_euros }}</label>{% if inpt.errors %}</summary>{% for err in inpt.errors %}{% if not forloop.first %}<br>{% endif %}{{ err }}{% endfor %}</details>{% endif %}
      </div>
    </div>
    {% endfor %}
  </div>
  {% if form.was_validated and form.errors %}
  <div class="row g-0 invalid-feedback" style="display: inline;">{% for err in form.errors %}{{ err }}{% if not forloop.last %}<br>{% endif %}{% endfor %}</div>
  {% endif %}
  <div class="container px-0"><div class="row g-0"><input class="form-control btn btn-primary" type="submit" value="OK" id="reservation-submit"></div></div>
</form>
{% endblock %}

djangosrh/concert/templates/concert/reservations.html
{% extends "core/base_template.html" %}
{% load currency_filter %}
{% block title %}{{ event.name }}{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-5">
      Il y a {{ event.reservation_set.count|plural:"réservation" }} pour {{ total_count|plural:"place" }}.
    </div>
    <div class="col-sm-2">
      <a class="link-primary" href="{% url 'concert:reservation_form' event.id %}">Nouvelle réservation</a>
    </div>
    <div class="col-sm-2">
      <a class="link-primary" href="{% url 'payments' %}">Gérer paiements</a>
    </div>
    <div class="col-sm-2">
      <a class="link-primary" href="{% url 'concert:export_csv' event.id %}">Exporter liste</a>
    </div>
    <div class="col-sm-1">
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Log Out</button>
      </form>
    </div>
  </div>
</div>
<ul>
{% for itm in event.reservation_items %}
  <li>{{ itm.total_count }} {% if itm.total_count == 1%}{{ itm.display_text }}{% else %}{{ itm.display_text_plural }}{% endif %}</li>
{% endfor %}
</ul>
{% if page_obj.has_previous or page_obj.has_next %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="link-primary" href="?page=1">&laquo; first</a>
            {% if page_obj.previous_page_number > 1 %}<a class="link-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>{% endif %}
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            {% if page_obj.next_page_number < page_obj.paginator.num_pages %}<a class="link-primary" href="?page={{ page_obj.next_page_number }}">next</a>{% endif %}
            <a class="link-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
<table>
  <thead>
    <tr>
      <th>Réservation</th>
      <th class="text-end">Places</th>
      <th class="text-end">Valeur</th>
      <th class="text-end">Payé</th>
      <th>Confirmer réception d'un paiement</th>
    </tr>
  </thead>
  <tbody>
    {% for reservation in reservations %}
    <tr>
      <td>
        <a class="link-primary" href="{% url 'concert:show_reservation' reservation.uuid %}">{{ reservation }}</a>
      </td>
      <td class="ps-1 text-end">{{ reservation.places }}</td>
      <td class="ps-1 text-end">{{ reservation.total_due_in_cents|cents_to_euros }}</td>
      <td class="ps-1 text-end">{{ reservation.total_received_in_cents|cents_to_euros }}</td>
      <td class="ps-1">{% if reservation.likely_payment_id %}<form method="POST" action="{% url 'concert:send_payment_reception_confirmation' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="hidden" name="payment_id" value="{{ reservation.likely_payment_id }}">
          <input type="hidden" name="reservation_id" value="{{ reservation.id }}">
          <input type="hidden" name="event_id" value="{{ event.id }}">
          <input type="submit" value="{{ reservation.likely_payment_other_name|default:reservation.likely_payment_other_account }}: {{ reservation.likely_payment_amount_in_cents|cents_to_euros }}"></form>{% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if page_obj.has_previous or page_obj.has_next %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="link-primary" href="?page=1">&laquo; first</a>
            {% if page_obj.previous_page_number > 1 %}<a class="link-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>{% endif %}
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            {% if page_obj.next_page_number < page_obj.paginator.num_pages %}<a class="link-primary" href="?page={{ page_obj.next_page_number }}">next</a>{% endif %}
            <a class="link-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}

djangosrh/concert/templates/concert/show_reservation.html
{% extends "core/base_template.html" %}
{% load currency_filter %}
{% block title %}{{ reservation.full_name }} - {{ reservation.event.name }}{% endblock %}
{% block content %}
<p>
  Votre réservation au nom de {{ reservation.full_name }} pour {{ reservation.places|plural:"place" }} le {{ reservation.event.date|french_date }} a été enregistrée.  Vous pouvez garder <a class="link-primary" href="{% url 'concert:show_reservation' reservation.uuid %}">cette page</a> dans vos favoris ou l'imprimer comme preuve de réservation.
</p>
<ul>
  {% for chc in choices %}
  <li>{{ chc.count|plural:chc.display_text_with_plural }}</li>
  {% endfor %}
</ul>
<p>
  Les tickets correspondant à votre commande seront à votre disposition à l'entrée.
  {% if remaining_amount_due_in_cents > 0 %}
  Le prix total est de {{ reservation.total_due_in_cents|cents_to_euros }} pour votre
  réservation{% if remaining_amount_due_in_cents != reservation.total_due_in_cents %}
  dont {{ remaining_amount_due_in_cents|cents_to_euros }} sont encore dûs
  {% endif %}.
  Nous vous saurions gré de déjà faire un virement pour cette somme avec la
  communication structurée <code>{{ reservation.bank_id|format_bank_id }}</code>
  sur le compte {{ reservation.event.bank_account }} (bénéficiaire
  {{ reservation.event.organizer_name }}; BIC {{ reservation.event.organizer_bic }})
  pour votre réservation, p.ex. en scannant ce code QR avec votre application
  bancaire mobile (testé avec Argenta, Belfius Mobile et BNP Paribas Fortis
  Easy Banking; incompatible avec Payconiq):<br>{{ payment_qrcode|safe }}
  {% elif reservation.total_due_in_cents > 0 %}
  Merci d'avoir déjà réglé l'entièreté des {{ reservation.total_due_in_cents|cents_to_euros }} dûs.
  {% endif %}
</p>
<p><a class="link-primary" href="mailto:{{ reservation.event.contact_email }}">Contactez-nous</a> si vous avez encore des questions.  Un tout grand merci pour votre présence le {{ reservation.event.date|french_date }}: le soutien de nos auditeurs nous est indispensable!</p>
<p>Ajoutez <a class="link-primary" href="{% url 'concert:show_reservation' reservation.uuid %}">cette page</a> à vos favoris ou scannez ce code QR pour suivre l'état actuel de votre réservation:<br>{{ page_qrcode|safe }}
{% endblock %}